version: '3'

services:
  cloudflare-dns-updater:
    image: cloudflare-dns-updater:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ZONE_ID=${ZONE_ID}
      - API_TOKEN=${API_TOKEN}
      - ALLOW_LIST=${ALLOW_LIST}
      - DENY_LIST=${DENY_LIST}
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped 