version: '3'

services:
  cloudflare-dns-updater:
    image: cloudflare-dns-updater:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    environment:
      - ZONE_ID=${ZONE_ID}
      - API_TOKEN=${API_TOKEN}
      - DNS_RECORDS_TO_UPDATE=${DNS_RECORDS_TO_UPDATE}
    restart: unless-stopped 